export const SMART_RECOMMENDATION_REQUEST = "SMART_RECOMMENDATION_REQUEST";
export const SMART_RECOMMENDATION_SUCCESS = "SMART_RECOMMENDATION_SUCCESS";
export const SMART_RECOMMENDATION_FAIL = "SMART_RECOMMENDATION_FAIL";
